#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Jan 17 01:30:14 CET 2020
# SW Build 2729669 on Thu Dec  5 04:48:12 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 9f825cd37dfa4a5091e3b2af3fe142cf --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot clock_div_tb_behav xil_defaultlib.clock_div_tb -log elaborate.log"
xelab -wto 9f825cd37dfa4a5091e3b2af3fe142cf --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot clock_div_tb_behav xil_defaultlib.clock_div_tb -log elaborate.log

